---
driver:
  name: vagrant
  provider: hyperv
  network:
  - ["public_network", bridge: "LAN"]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

#transport:
 # name: WinRM
 # username: vagrant
 # password: vagrant
 # elevated: true

verifier:
  name: inspec

platforms:
  #- name: ubuntu-16.04
  - name: centos-7
  #- name: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[apache9::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
